---
version: 2.1

executors:
  debian:
    docker:
    - image: debian:bookworm
  github:
    docker:
    - image: cibuilds/github:0.13
  ruby:
    docker:
    - image: circleci/ruby:latest

jobs:
  build:
    executor: debian

    steps:
    - run: apt-get update
    - run: apt-get -y install build-essential git openssh-client musl-dev musl-tools libsdl2-dev
    - checkout
    - run: mkdir -v -p build/amd64
    - run: make
    - run: mv -v sproxy usb_reset wait_next_second cursor_disable.so build/amd64/
    - persist_to_workspace:
        root: .
        paths:
        - build
    - store_artifacts:
        path: build

  package:
    executor: ruby

    steps:
    - run: gem install fpm
    - checkout
    - attach_workspace:
        at: .
    - run: gem install package_cloud
    - run: mkdir -v -p release
    - run: >
        fpm -n sproxy -s dir -t deb -a amd64 -v ${CIRCLE_TAG#v} -p release \
           build/amd64/sproxy=/usr/bin/ \
           build/amd64/usb_reset=/usr/bin/ \
           build/amd64/wait_next_second=/usr/bin/ \
           build/amd64/cursor_disable.so=/usr/lib/ \
           README.md=/usr/share/doc/sproxy/
    - run: package_cloud push fosdem/video-team/debian/bookworm release/*deb
    - store_artifacts:
        path: release
    - persist_to_workspace:
        root: .
        paths:
        - release

  release:
    executor: github

    steps:
    - run: apk add fakeroot
    - attach_workspace:
        at: .
    - run: mkdir -v -p release
    - run: fakeroot tar -czvf release/sproxy-${CIRCLE_TAG}.amd64.tar.gz -C build/amd64 sproxy usb_reset wait_next_second cursor_disable.so
    - run: cd release && sha256sum sproxy-*.tar.gz *deb > sha256sums.txt
    - run: > 
        ghr \
          -u "${CIRCLE_PROJECT_USERNAME}" \
          -r "${CIRCLE_PROJECT_REPONAME}" \
          -c "${CIRCLE_SHA1}" \
          -delete \
          "${CIRCLE_TAG}" \
          ./release/

workflows:
  version: 2
  video-sproxy:
    jobs:
    - build:
        filters:
          tags:
            only: /.*/
    - package:
        requires:
        - build
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
    - release:
        requires:
        - build
        - package
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
