---
version: 2.1

jobs:
  build:
    docker:
    - image: debian:stable

    steps:
    - checkout
    - run: apt-get update
    - run: apt-get -y install build-essential musl-dev musl-tools crossbuild-essential-armhf crossbuild-essential-arm64
    - run: mkdir -v -p build/amd64 build/armhf build/arm64
    - run: make
    - run: mv -v sproxy build/amd64/sproxy
    - run: CC=arm-linux-gnueabihf-gcc make
    - run: mv -v sproxy build/armhf/sproxy
    - run: CC=aarch64-linux-gnu-gcc make
    - run: mv -v sproxy build/arm64/sproxy
    - persist_to_workspace:
        root: .
        paths:
        - build
    - store_artifacts:
        path: build

  release:
    docker:
    - image: cibuilds/github:0.13

    steps:
    - run: apk add fakeroot
    - attach_workspace:
        at: .
    - run: mkdir -v -p release
    - run: fakeroot tar -czvf release/sproxy-${CIRCLE_TAG}.amd64.tar.gz -C build/amd64 sproxy
    - run: fakeroot tar -czvf release/sproxy-${CIRCLE_TAG}.armhf.tar.gz -C build/armhf sproxy
    - run: fakeroot tar -czvf release/sproxy-${CIRCLE_TAG}.arm64.tar.gz -C build/arm64 sproxy
    - run: cd release && sha256sum sproxy-*.tar.gz > sha256sums.txt
    - run: > 
        ghr \
          -u "${CIRCLE_PROJECT_USERNAME}" \
          -r "${CIRCLE_PROJECT_REPONAME}" \
          -c "${CIRCLE_SHA1}" \
          -delete \
          "${CIRCLE_TAG}" \
          ./release/

workflows:
  version: 2
  video-sproxy:
    jobs:
    - build:
        filters:
          tags:
            only: /.*/
    - release:
        requires:
        - build
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
