---
version: 2.1

jobs:
  build:
    docker:
    - image: circleci/golang:1.11

    steps:
    - checkout
    - run: sudo apt-get update
    - run: sudo apt-get -y install build-essential musl-dev musl-tools crossbuild-essential-armhf
    - run: mkdir -v build
    - run: make
    - run: mv -v sproxy build/sproxy-amd64
    - run: CC=arm-linux-gnueabihf-gcc make
    - run: mv -v sproxy build/sproxy-armhf
    - persist_to_workspace:
        root: .
        paths:
        - build
    - store_artifacts:
        path: build

  release:
    docker:
    - image: circleci/golang:1.11

    steps:
    - run: sudo apt-get update
    - run: sudo apt-get -y install fakeroot
    - run: mkdir -v -p ${HOME}/bin
    - run: curl -L 'https://github.com/aktau/github-release/releases/download/v0.7.2/linux-amd64-github-release.tar.bz2' | tar xvjf - --strip-components 3 -C ${HOME}/bin
    - attach_workspace:
        at: .
    - run: cd build && fakeroot tar -czvf ../sproxy-${CIRCLE_TAG}.amd64.tar.gz sproxy-amd64
    - run: cd build && fakeroot tar -czvf ../sproxy-${CIRCLE_TAG}.armhf.tar.gz sproxy-armhf
    - run: > 
        for tarfile in sproxy-*.tar.gz ; do
          ${HOME}/bin/github-release upload \
            --user "${CIRCLE_PROJECT_USERNAME}" \
            --repo "${CIRCLE_PROJECT_REPONAME}" \
            --tag "${CIRCLE_TAG}" \
            --name "${tarfile}" \
            --file "${tarfile}"
        done

workflows:
  version: 2
  video-sproxy:
    jobs:
    - build:
        filters:
          tags:
            only: /.*/
    - release:
        requires:
        - build
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
